### PR TITLE
Restrict file extensions

### PR DESCRIPTION
**Pull request by genjohnson**
As part of our response to [Drupal file upload by anonymous or untrusted users into public file systems -- PSA-2016-003](https://www.drupal.org/psa-2016-003), remove the ability for users to allow arbitrary file extensions for uploads through webforms to avoid having potentially malicious files uploaded (e.g., .exe).

This pull request:
- Removes access to the "additional types" textfield for file upload form components.
- Uses a modified version of theme_webform_edit_file_extensions() to remove the "Additional types" row from the "Allowed file extensions" table.
- Removes any custom file extensions that had previously been set in the "additional types" field.

With this patch applied, the "Allowed file extensions" row should be removed from the Validation field set/tab of file upload fields when using the Form Builder module (_Form builder_ tab) or just the Webform module (_Form components_ tab).

Before patch is applied:
screen shot 2016-10-11 at 3 25 18 pm
screen shot 2016-10-11 at 3 26 16 pm

After patch is applied:
screen shot 2016-10-11 at 3 23 56 pm
screen shot 2016-10-11 at 3 27 05 pm

### CODE REVIEW

**Comment by genjohnson** [comment]
Thanks to @briand44 for thoroughly testing this!

Based on his feedback, I've fix how custom extensions are removed so that those extensions are _actually_ restricted. I've also added support for removing multiple custom extensions from the same field plus outputting a message about any extensions that are removed during the update.

This could use another review when someone has a moment.

**Comment by genjohnson** [comment]
Brian and I talked about what to do in the case that a site has an additional file extension that we should allow.

When this database update is run, it will print a message for each webform that had custom extensions allowed that identified which extensions have been removed, so we can watch during dev & test updates if we can expect to run into this case in production.


The plan is to review the output and notify clients of any extensions that are removed. If any clients do need additional extensions, then we will allow admins to provide custom extensions.

**Comment by adamdelaney** [comment]
I just received an email in regards to allowed file extensions for webforms from Engineering, so yes, I believe we will need to allow additional extensions.

**Comment by briand44** [comment]
Is restricting these even necessary? When using file type "js" webform renames it to "js.txt" anyway, so webform may be handling some of the harmful file extensions.

**Comment by adamdelaney** [comment]
Here's a list of ext requested from Eng. 

pri, idw, stl, 3ds, 3dm, stp, step, and matercam files.

**Comment by genjohnson** [comment]
Summary of an in-person discussion about the concerns/questions raised by @briand44 and @adamdelaney:

- While some file types (such as .js) are re-named when uploaded (e.g., .js.txt), we cannot count on this feature to protect sites. For example, I was able to upload a .exe file without it being renamed.
- It seems like it would be a hassle for people with access to the files submitted to need to remove ".txt" from the file name.
- Any file can be uploaded by using a .zip.

The conversation ended with the agreement to move forward with removing access to specify custom file types to allow, and instruct users to use .zips for these cases.

I will work on adding a message about using zips to the validation settings form.

**Comment by genjohnson** [comment]
Added comment about collecting files of additional types: `To collect files of additional types, allow the zip type. A respondent can then upload files of additional types by compressing the files into a zip file before uploading.`

I think this pull request is ready to be merged in.

**Comment by brandonneil** [comment]
I moved the creation of the private file system out of sitenow_forms and into the install profile. It felt weird to me that we were doing it here in the sitenow_forms module when it is a site-wide feature we're enabling. I also used hook_update_dependencies() to ensure that the private file system is configured before we try moving webform submission files into the private file system.

It's a bit more complex with this extra hook, but it feels more natural to me that both the update hook and install task for the private file system happen at the same place now.

**Pull request merged**
